### ISSUE TITLE
A Puzzle About InductorProlog Example

### ISSUE THREAD

**Issue by aresfor** [EricZinda/InductorSoftwareBlogComments#1]
https://blog.inductorsoftware.com/blog/prolog
    ->(Paragragh)Evaluating a Prolog Rule

In this example, under the conditions of downtown, the distance to uptown is 5, why is the situation where the distance <=2 not satisfied is added to the result, I haven't actually tried it myself, but I think this should be wrong?

**Comment by aresfor** [comment]
![example](https://user-images.githubusercontent.com/62842879/203096418-aa0d8eb8-4172-4b10-af7f-8a97fa8df258.png)
I just tried this example and didn't go to uptown and it's a real errata, but it's still excellent HTN Blog helping me understand these

**Comment by EricZinda** [comment]
Thanks for pointing this out!  Yes, that is a bug. Since uptown is 5 units away and the rule says the distance should be <= 2, that should not be in the answer.  I'm not sure how it got in there!  I just fixed it.  Thanks for reporting!

Glad it helped you understand HTNs! I really struggled with it at first.
